export const FETCH_PRODUCT_LIST_START = "FETCH_PRODUCT_LIST_START"
export const FETCH_PRODUCT_LIST_SUCCESS = "FETCH_PRODUCT_LIST_SUCCESS"
export const FETCH_PRODUCT_LIST_FAILED = "FETCH_PRODUCT_LIST_FAILED"