export const SPLASH_SCREEN = "SPLASH_SCREEN";
export const HOME_SCREEN = "HOME_SCREEN";
export const PRODUCT_LISTING_SCREEN = "PRODUCT_LISTING_SCREEN";
export const PRODUCT_SALE_SETUP_SCREEN = "PRODUCT_SALE_SETUP_SCREEN";
export const PRODUCT_SALE_SCREEN = "PRODUCT_SALE_SCREEN";